- hosts: "{{ service }}-{{ env }}"
  become: yes
  roles:
    - { role: datadog.datadog, become: yes }
    - datadog-agent-ubuntu18-laravel-nginx-php-fpm
    - php7.2-fpm
    - supervisord
  vars_files:
    - vars/datadog-agent-base
    - vars/datadog-agent-ubuntu18-laravel-nginx-php-fpm-supervisord